# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ai.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mediaAi.chatbot import chat


class Ui_ai(object):

    
    def chating(self,text):
      self.textBrowser.setText("")
      if text!="":
        res=chat(text)
        self.textBrowser.setText(res)

    def setupUi(self, ai):
        ai.setObjectName("ai")
        ai.resize(800, 610)
        ai.setMinimumSize(QtCore.QSize(800, 610))
        ai.setMaximumSize(QtCore.QSize(800, 610))
        self.centralwidget = QtWidgets.QWidget(ai)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 811, 611))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../-1x-1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 90, 268, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.add_to_fav_btn = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.chating(self.textEdit.toPlainText()))
        self.add_to_fav_btn.setGeometry(QtCore.QRect(40, 160, 141, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.add_to_fav_btn.setFont(font)
        self.add_to_fav_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_to_fav_btn.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius:10px;\n"
"")
        self.add_to_fav_btn.setIconSize(QtCore.QSize(24, 24))
        self.add_to_fav_btn.setObjectName("add_to_fav_btn")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(40, 220, 268, 231))
        self.textBrowser.setObjectName("textBrowser")
        ai.setCentralWidget(self.centralwidget)

        self.retranslateUi(ai)
        QtCore.QMetaObject.connectSlotsByName(ai)

    def retranslateUi(self, ai):
        _translate = QtCore.QCoreApplication.translate
        ai.setWindowTitle(_translate("ai", "MainWindow"))
        self.label_2.setText(_translate("ai", "Write Your Music Question"))
        self.add_to_fav_btn.setText(_translate("ai", "Answer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ai = QtWidgets.QMainWindow()
    ui = Ui_ai()
    ui.setupUi(ai)
    ai.show()
    sys.exit(app.exec_())
